### ISSUE TITLE
Executable: Expose number of cores/threads/gpus/etc as environment variables to scripts

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#1483]
Currently we pass the number of cores and number of threads as script variables to the executable scripts for each code.  I'd like to additionally pass them as environment variables. It makes it a bit neater, but more importantly it would mean we no longer need separate scripts for mpi and non mpi version and also allow the dynamically created job classes (wrap_executable) to take more than one core.

- [x] Set env vars run GenericJob.run_static
- [ ] Remove error when trying to run a job with more than one core when no mpi executable is present
- [ ] Emit a warning in this case
```[tasklist]
### Tasks
- [ ] Update executable script documentation
```
